language: python
sudo: required

# which python versions to test
python:
  - "3.6"
  - "3.7"

# Cache directory $HOME/.cache/pip
cache: pip
  
# command before installation: install all dependencies and run CMAKE config
before_install:
  - sudo apt-get install gfortran
  - sudo apt-get install openmpi-bin libopenmpi-dev
  - sudo apt-get install libhdf5-openmpi-dev  
  - python -m pip install --upgrade pip
  - python -m pip install Cython

# command to install project
install:
  - python -m pip install .

before_script:
  - export MESH_DIR=$TRAVIS_BUILD_DIR/mesh

# command to run tests
script:
  - python -m pytest manapy
